---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hono-service-device-registry
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-service-device-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-service-device-registry
      group: {{ .Values.project.groupId }}
  template:
    metadata:
      labels:
        app: hono-service-device-registry
        version: "{{ .Chart.AppVersion }}"
        group: {{ .Values.project.groupId }}
    spec:
      initContainers:
      {{- if eq .Values.jaeger.enabled true}}
        - name: wait-for-jaeger-agent
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Values.jaeger.agentHost }}; do echo waiting for {{ .Values.jaeger.agentHost }}; sleep 2; done;']
      {{- end}}
        - name: copy-example-data
          image: busybox
          command:
            - sh
            - -c
            - cp -u /tmp/hono/example-device-identities.json /var/lib/hono/device-registry/device-identities.json;
              cp -u /tmp/hono/example-credentials.json /var/lib/hono/device-registry/credentials.json;
              cp -u /tmp/hono/example-tenants.json /var/lib/hono/device-registry/tenants.json
          volumeMounts:
            - mountPath: /tmp/hono
              name: conf
            - mountPath: /var/lib/hono/device-registry
              name: registry
      containers:
      - image: {{ .Values.honoContainerRegistry }}/eclipse/hono-service-device-registry:{{ .Values.honoImageTag }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-service-device-registry
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: amqps
          containerPort: 5671
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        {{- if eq .Values.jaeger.enabled true}}
        - name: JAEGER_SERVICE_NAME
          value: hono-service-device-registry
        {{- range $key, $value := .Values.jaeger.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end}}
        - name: _JAVA_OPTIONS
          value: "{{ .Values.defaultJavaOptions }}"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /var/lib/hono/device-registry
          name: registry
        - mountPath: /etc/hono
          name: conf
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 10
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry
      - name: conf
        secret:
          secretName: hono-service-device-registry-conf
