# Below are only the static parts of the menu. In the build pipeline (jenkins/Hono-Website-Pipeline.groovy) 
# menu entries are appended for every version in file versions_supported.csv.

[[menu.main]]
    name = "Documentation"
    weight = -30000

[[menu.main]]
    parent = "Documentation"
    name = "Development"
    url  = "/docs/latest"
    weight = -10000
