---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hono-adapter-amqp-vertx
    version: "{{ .Chart.AppVersion }}"
    group: {{ .Values.project.groupId }}
  name: hono-adapter-amqp-vertx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-adapter-amqp-vertx
      group: {{ .Values.project.groupId }}
  template:
    metadata:
      labels:
        app: hono-adapter-amqp-vertx
        version: "{{ .Chart.AppVersion }}"
        group: {{ .Values.project.groupId }}
    spec:
      {{- if eq .Values.jaeger.enabled true}}
      initContainers:
        - name: wait-for-jaeger-agent
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Values.jaeger.agentHost }}; do echo waiting for {{ .Values.jaeger.agentHost }}; sleep 2; done;']
      {{- end}}
      containers:
      - image: {{ .Values.honoContainerRegistry }}/eclipse/hono-adapter-amqp-vertx:{{ .Values.honoImageTag }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-adapter-amqp-vertx
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: amqps
          containerPort: 5671
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        {{- if eq .Values.jaeger.enabled true}}
        - name: JAEGER_SERVICE_NAME
          value: hono-adapter-amqp
        {{- range $key, $value := .Values.jaeger.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end}}
        - name: _JAVA_OPTIONS
          value: "{{ .Values.defaultJavaOptions }}"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /etc/hono
          name: conf
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 10
      volumes:
      - name: conf
        secret:
          secretName: hono-adapter-amqp-vertx-conf
