# Copyright (c) 2020, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
# This workflow will build all of Hono's components, run unit tests and create
# Docker images. Finally, the integration tests are run.
# The job uses a matrix for the distinct device registry implementations. Thus,
# for each registry implementation, the workflow is run on a separate VM.

name: Build and run integration tests

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        device-registry: [file,jdbc,mongodb]
        include:
        # Use Quarkus JVM images: file registry, AMQP messaging, Command Router with embedded cache
        - device-registry: file
          commandrouting-cache: embedded
          messaging-type: amqp
        # Use Quarkus JVM images: jdbc registry, Kafka messaging, Command Router with embedded cache
        - device-registry: jdbc
          commandrouting-cache: embedded
          messaging-type: kafka
        # Use Quarkus JVM images: mongodb registry, Kafka messaging, Command Router with data grid
        - device-registry: mongodb
          commandrouting-cache: server
          messaging-type: kafka

    name: "Use ${{ matrix.device-registry }} registry, ${{ matrix.messaging-type }} messaging with ${{ matrix.commandrouting-cache }} cache"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "17"
        cache: "maven"
    - name: Build all components (incl. unit tests) and run integration tests
      run: mvn install -B -e -DcreateJavadoc=true -DCI=$CI -Dhono.deviceregistry.type=${{ matrix.device-registry }} -Dhono.messaging-infra.type=${{ matrix.messaging-type }} -Dhono.commandrouting.cache=${{ matrix.commandrouting-cache }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pbuild-docker-image,jaeger,run-tests
